# This workflow will install Python dependencies and lint with a single version of Python

name: mypy typechecking

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  typechecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml sqlalchemy connexion requests flask mypy appdirs authlib
          pip install types-PyYAML types-requests types-flask types-itsdangerous
      - name: Run typechecking
        run: |
          scripts/verify-type-correctness.sh
